### ISSUE TITLE
参加者の方に参考になりそうな情報の共有について

### ISSUE THREAD

**Issue by uhobeike** [furo-org/VTC2018#11]
VTCで使用するUnreal Engineの環境構築からROS(LIO-SAM)を使用してマップ作成を行うまでの一連の作業と結果を以下のブログサイトにまとめました。また、実際に取得したrosbagデータの共有リンクも載せてあります。

https://beike-re.hatenablog.com/entry/VTC/LIO-SAM/3d-mapping?_ga=2.177404837.1219929223.1598519329-703849559.1590685405

VTCに挑戦する方がアクセスしやすい場所にリンクを張っていただけると、少しでも助けになるかと考えています。

**Comment by yosagi** [comment]
情報ありがとうございます。README.mdよりリンクを張りたいと思います。

なお、こちらの環境でもご紹介頂いた手順を試してみました。用意できた環境はブログで使用されている物とは異なり ubuntu 20.04, ROS Noetic でしたので、そのままではビルドできないものがありました。これは以下の作業で同様に動くことが確認できました。
1. gstamはLIO-SAMが指定する4.0.2はコンパイルできない。github の develop ブランチならOK。
2. LIO-SAM の依存パッケージを rosdep でインストール
2. LIO-SAM/include/utility.hとLIO-SAM/CMakeLists.txtを修正する必要がある。
差分は以下の通りです。

``` diff
diff --git a/include/utility.h b/include/utility.h
index 74e742e..33bf44c 100644
--- a/include/utility.h
+++ b/include/utility.h
@@ -14,7 +14,8 @@
 #include <visualization_msgs/Marker.h>
 #include <visualization_msgs/MarkerArray.h>

-#include <opencv/cv.h>
+#include<opencv2/opencv.hpp>
 
 #include <pcl/point_cloud.h>
 #include <pcl/point_types.h>
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 64859c6..4990c63 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -2,7 +2,7 @@ cmake_minimum_required(VERSION 2.8.3)
 project(lio_sam)
 
 set(CMAKE_BUILD_TYPE "Release")
-set(CMAKE_CXX_FLAGS "-std=c++11")
+set(CMAKE_CXX_FLAGS "-std=c++14")
 set(CMAKE_CXX_FLAGS_RELEASE "-O3 -Wall -g -pthread")
 
 find_package(catkin REQUIRED COMPONENTS
```

**Comment by uhobeike** [comment]
ありがとうございます。よろしくお願いします。:bow:
>情報ありがとうございます。README.mdよりリンクを張りたいと思います。

とても助かります。
確かに、ubuntu 20.04, ROS Noeticを使用している方もいらっしゃると思うので、上記の差分を参考に記事に追加しようと思います。
>なお、こちらの環境でもご紹介頂いた手順を試してみました。用意できた環境はブログで使用されている物とは異なり ubuntu 20.04, ROS Noetic でしたので、そのままではビルドできないものがありました。これは以下の作業で同様に動くことが確認できました。

**Comment by yosagi** [comment]
リンク先ですが、?_ga= 以降の文字列も残しておいた方がいいですか?

**Comment by uhobeike** [comment]
すみません、残さないで大丈夫です。

以下のリンクでお願いします。
https://beike-re.hatenablog.com/entry/VTC/LIO-SAM/3d-mapping

**Comment by yosagi** [comment]
こんなリンクでどうでしょうか。

**Comment by uhobeike** [comment]
良いと思います。
ありがとうございます。:bow:

**Comment by ngtroku** [comment]
突然失礼します。記事（https://beike-re.hatenablog.com/entry/VTC/LIO-SAM/3d-mapping#Ubuntu2004-ROS-Noetic%E3%81%AE%E5%A0%B4%E5%90%88）
を拝見させて頂きました。gtsamのインストールに関してなのですが、私の環境ではdevelopブランチを使うのではなくgtsam4.0.3のzipファイルをダウンロードし、解凍することでLIO-SAMが起動しました。
　また、LIO-SAMのissue（https://github.com/TixiaoShan/LIO-SAM/issues/206）
ではutility.hのコードを書き換える件に関して、opencvのincludeをpclヘッダの下に書き換えることで動作するとの報告がありました。私の環境でもpclヘッダの下にopencvのincludeを置くことで正しくインストールできました。
1.  gtsam4.0.3をzipからダウンロードしてLIO-SAMを起動する方法
2.  <opencv2/opencv.hpp>をpclヘッダの下でincludeする
以上の2点に関して日本語ソースが無さそうなので私の記事で紹介させていただいてもよろしいでしょうか。
