### ISSUE TITLE
VTC実行中にロボットが走行しない

### ISSUE THREAD

**Issue by ghost** [furo-org/VTC2018#13]
VTCを実行した際にロボットを前方に走行させようとしたところ、
ブループリントの設定を調整しても、CageClientを介しても、
全く動かずに困っています（LiDARは問題なく動作するようです）。
Unreal Engineのバージョンは4.25.4です。（4.25.3は配布が終了していました。）
また、UE4のアウトプットログには以下のようなエラーが出力されていました。

LogPhysicsCore: Error: PHYSX: (D:\Build\++Fortnite\Sync\Engine\Source\ThirdParty\PhysX3\PhysX_3.4\Source\PhysX\src\NpScene.cpp 926) eINVALID_OPERATION : PxScene::addArticulation(): Articulation already assigned to a scene. Call will be ignored!

そしてパッケージ済みバイナリからであれば、CageClient経由で動かすことができました。
このエラーはUnreal Engineのバージョンに起因するものなのでしょうか。
どうかご意見のほど、よろしくお願い致します。

**Comment by yosagi** [comment]
報告ありがとうございます。
確認したところ、ブループリントからの指令の処理が不完全なためブループリントから走行指令を送っても車輪が駆動されていませんでした。こちらは近いうちに修正いたします。
一方、CageClientからの指令で走らないという現象は再現しませんでした。再現性があるようでしたらもう少し詳しい状況を教えていただけますでしょうか。
なお、こちらでは以下の環境で動作確認を行いました。

+ UE 4.25.4
+ VTC 現在のTC2020ブランチおよびv0.202009.04タグ
+ CageClient 現在のmasterブランチおよび53c51f5

以上、よろしくお願いします。

**Comment by ghost** [comment]
yosagi様

ご返信ありがとうございます。
CageClientについてですが、
sanpleRunを使ってロボットを前方に進めようとしたところ、

connecting to: XXX.XXX.XXX.XXX

と表示されたままプログラムの実行が進みません。
しかし、この現象は現時点ではUE 2.45.4から実行した場合のみ発生し、
UE 4.25.3や、パッケージ済みバイナリでVTCを動かした場合は起きません。
なお、パッケージ済みバイナリは配布のVTC 2020/5/28版を利用しています。
そしてCageClientのバージョンは恐らく64f1ab5だと思います。
使用しているOSはUbuntu 18.04LTSです。
また、cage_ros_stackで動作するかどうかの確認はしていません。

以上です。よろしくお願い致します。

**Comment by yosagi** [comment]
追加情報ありがとうございます。
ひとまずブループリントからも動くように修正しました。
この修正を適用済みの状態で動作確認したところCageClientのSampleRunで動かない現象は起きませんでした。ご確認いただけますでしょうか。
こちらでは、CageClientは現在のmasterブランチと64f1ab5の2種で、UE4は4.25.4で確認しました。

VTCをfix-setVWブランチにしてgit submodule update後、Unreal Editor が一つも起動していない状態で Visual Studio でビルドしてください。

connecting to.. で止まるというのはファイアーウォールが何かしている可能性も考えられますが、エンジンのバージョン等で挙動が変わるというのはそれでは説明が付かないような気もします。

**Comment by ghost** [comment]
yosagi様

速やかなご対処のほど、ありがとうございました。
しかし、残念ながらこちらの環境で試したところ、
特に問題の改善は見られませんでした。
CageClientのsampleRunを使ってもやはりロボットは動かず、connecting to...で止まってしまいます。
ただし、windows側のPCとubuntu側のPCとの通信状態を確認したところ、
sampleRunを実行した際に、windows側は何らかのデータの受信をしているようなので、
VTC内で何かが起こっているような気がしております。

以上です。よろしくお願い致します。

**Comment by yosagi** [comment]
Connecting to.. 周りでの状況をもう少し確認させてください。
現在の CageClient のmasterブランチの実装では cage.connect() でロボットの情報を問い合わせます。このとき、Unreal Editor の Output Log に以下のようなメッセージが表示されます。これは出ているでしょうか。(細かい数値などは同じにならないかもしれません)
```
LogTemp: Warning: GetActorMeta[CommActor1]: Q:GeoReferenceBP_2 meta:{"Transform":{"translation":{"x":27340,"y":18120,"z":85},"rotation":{"x":0,"y":-0,"z":0.68008130788803101,"w":0.73313665390014648}},"GeoLocation":{"latitude":{"x":36,"y":4,"z":59.490001678466797},"longitude":{"x":140,"y":4,"z":36.860000610351562}}}
LogTemp: Warning: GetActorMeta[CommActor1]: Q:PuffinBP_11 meta:{"Transform-Lidar":{"translation":{"x":-21.999782562255859,"y":0.00080351874930784106,"z":61.774456024169922},"rotation":{"x":0,"y":-1.7621459846850485e-12,"z":0,"w":1}},"TreadWidth":38,"ReductionRatio":15,"WheelPerimeterL":62.793972015380859,"WheelPerimeterR":62.793972015380859,"Transform-IMU":{
"translation":{"x":-9.9994468688964844,"y":10.000075340270996,"z":19.993860244750977},"rotation":{"x":0,"y":-1.7621459846850485e-12,"z":0,"w":1}}}
```

出ていない場合、CageClientの sampleConsole.py を使ってコマンドを送ってみて通信部分の動作確認をしてもらえませんでしょうか。
sampleConsole.pyを動かすには pyzmq が必要なのでまずこれをインストールします。
```
pip install pyzmq
```
次に適当なコンソールコマンドを送ります。
```
./sampleConsole.py [VTCのIP] cage.lidar.broadcast
```
うまく通信できている場合の実行結果は例えば以下の通りです。
```
$ ./sampleConsole.py 192.168.1.13 cage.lidar.broadcast
connecting to  tcp://192.168.1.13:54323
{'Input': 'cage.lidar.broadcast', 'Type': 'Console'}
{
 "Type" : "Console",
 "Result" : "cage.Lidar.Broadcast = \"0\"      LastSetBy: Constructor"
}
```
このときUnreal EditorのOutput Logに以下のメッセージが出るはずです。
```
LogTemp: Warning: Console command requested: cage.lidar.broadcast
Cmd: cage.lidar.broadcast
```
VTCが動いていない場合など正しくコマンドを送れなかった場合には例えば次のようになります。
```
$ ./sampleConsole.py 192.168.1.13 cage.lidar.broadcast
connecting to  tcp://192.168.1.13:54323
{'Input': 'cage.lidar.broadcast', 'Type': 'Console'}
Traceback (most recent call last):
  File "./sampleConsole.py", line 35, in <module>
    rep=sock.recv()
  File "zmq/backend/cython/socket.pyx", line 791, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 827, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 20, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable
```

これらが期待通り動作しない場合、Play直後のOutput Logを見て、通信チャネルが正しく準備できているか確認してください。VTCは今のところTCP 54321とTCP54323の2つのポートを使用します。他のアプリケーション(例えば別のVTCとか)がここを使っている場合通信チャネルの初期化に失敗します(が、画面上ではLogを見る以外確認する手段がありません)。
失敗している場合以下のようなログがOutput Logに出ます。
```
LogTemp: Warning: Message endpoint ready: 37999CFE4F5055B5484AF78D01F00D25
LogTemp: Warning: ACommActor::FImpl created
LogTemp: Warning: ZContext ready
LogTemp: Warning: ZSocket binding to tcp://*:54321
LogTemp: Error: Could not bind ReportSocket : -100 [Unknown error]
```
うまくいっている場合は次のようになります。
```
LogTemp: Warning: Message endpoint ready: F816D49E4A9D591EA85D5B8DBB40AE80
LogTemp: Warning: ACommActor::FImpl created
LogTemp: Warning: ZContext ready
LogTemp: Warning: ZSocket binding to tcp://*:54321
LogTemp: Warning: ReportSocket (tcp://*:54321) and CmdSocket (tcp://*:54323) are ready
```

以上、ご確認よろしくお願いいたします。

**Comment by ghost** [comment]
yosagi様

ブループリントを使ってもロボットが動かない問題につきましては、
ブランチの変更がうまく反映されていないのが原因だったようです。
ブループリントを使った場合にロボットを動かすことができることを確認しました。
ありがとうございました。
しかし、CageClientのsampleRunからはまだ動かせません。
現在の状況を順を追って説明致します。

先日の返信内容をもとにチェックを行ったところ、
まず、Output Logに、
```
LogTemp: Warning: GetActorMeta[CommActor1]: Q:GeoReferenceBP_2 meta:{"Transform":{"translation":{"x":27340,"y":18120,"z":85},"rotation":{"x":0,"y":-0,"z":0.68008130788803101,"w":0.73313665390014648}},"GeoLocation":{"latitude":{"x":36,"y":4,"z":59.490001678466797},"longitude":{"x":140,"y":4,"z":36.860000610351562}}}
LogTemp: Warning: GetActorMeta[CommActor1]: Q:PuffinBP_11 meta:{"Transform-Lidar":{"translation":{"x":-21.999782562255859,"y":0.00080351874930784106,"z":61.774456024169922},"rotation":{"x":0,"y":-1.7621459846850485e-12,"z":0,"w":1}},"TreadWidth":38,"ReductionRatio":15,"WheelPerimeterL":62.793972015380859,"WheelPerimeterR":62.793972015380859,"Transform-IMU":{
"translation":{"x":-9.9994468688964844,"y":10.000075340270996,"z":19.993860244750977},"rotation":{"x":0,"y":-1.7621459846850485e-12,"z":0,"w":1}}}
```
なる文面は出力されませんでした。
そしてCageClientのsampleConsole.pyを実行したところ、
`zmq.error.Again: Resource temporarily unavailable`
と表示され、正しく動いていないようでした。
そのため、もう一度Output Logを見直したところ、
通信チャネル関係の出力について、
`
LogTemp: Warning: ReportSocket (tcp://*:54321) and CmdSocket (tcp://*:54323) are ready
`
と出力されていたため、通信チャネルの初期化は問題ないようです。

以上です。よろしくお願い致します。

**Comment by yosagi** [comment]
確認ありがとうございます。
VTC側は待ち受け開始しているにもかかわらず接続できない、ということになりますね。
同じPC、ネットワーク構成で、パッケージ版や 4.25.3に対して sampleConsole.py で接続を試みた場合は成功しますでしょうか。念のためこちらもご確認いただけますでしょうか。
よろしくお願いします。

**Comment by ghost** [comment]
yosagi様

確認したところ、パッケージ版、4.25.3版いずれについても動作確認ができました。
また，sampleRunも動くようです。
よろしくお願い致します。

**Comment by yosagi** [comment]
確認ありがとうございます。
手元で再現しないのが苦しいところですが、もう少しお付き合いください。
現在の [fix-setVWブランチ](https://github.com/furo-org/VTC/tree/fix-setVW) でパッケージしたものを作ってみました。[ここ(https://1drv.ms/u/s!AkekAlL4McuXlwu6xpbDfAN_TO2_?e=MEE5qB)](https://1drv.ms/u/s!AkekAlL4McuXlwu6xpbDfAN_TO2_?e=MEE5qB)に置いておきますので、こちらも sampleConsole, sampleRun 双方試していただけますでしょうか。

また、Unreal Editor でPlayの横のドロップダウンメニューから Standalone Game を選択するとパッケージ版に近いものが起動します。こちらではどうでしょうか。

**Comment by ghost** [comment]
yosagi様

すみません、CageClientでの動作確認がすべて成功しました。
CageClientが正しく動かなかったのは、新しいUnreal Engineを
インストールした際にファイアーウォールの設定情報が変更されていたことが原因のようです。
設定を修正すると問題なく動作しました。
ご心労おかけして申し訳ございません。
よろしくお願い致します。

**Comment by yosagi** [comment]
ありがとうございます。動いて良かったです。
ファイアーウォールについてドキュメントでも書いておく必要がありますね。
また何かありましたら報告よろしくお願いします。
