### ISSUE TITLE
UEのバージョンについて

### ISSUE THREAD

**Issue by asmsuechan** [furo-org/VTC2018#5]
開発者の方々こんにちは。

https://github.com/furo-org/VTC/commit/aac5f976efe37ab3fe930b751726286941e573cc  このコミットを見るとUE4.25対応が行われているようですがドキュメント (https://github.com/furo-org/VTC/blob/TC2019/docs/editor.md )には4.24.3が指示されています。
そして今手元でUE4.24.3を使い環境構築をしており、VTC.uprojectを開いてビルドを行うと`VTC could not be compiled. Try rebuilding from source manually.`というエラーが発生して失敗します。現状このプロジェクトは4.24.3でも動作しますか？それとも4.25へのバージョンアップが必要ですか？

**Comment by yosagi** [comment]
コメントありがとうございます。
UE4.25対応時のドキュメントの更新漏れでした。現在のデフォルトブランチではUE4.25が対応するバージョンとなっています。
UE4.24で動かすにはsubmoduleで参照している PxArticulationLink プラグインを[一つ前のcommit](https://github.com/yosagi/PxArticulationLink/commit/d5cd78c2519b61ec0503086dd6bb6863a32a58ca) に巻き戻す必要があります。

```
cd Plugins/PxARticulationLink
git checkout d5cd78c2519
```
手元の環境ではこれでビルドが通ることを確認しました。お試しいただけますでしょうか。

**Comment by asmsuechan** [comment]
回答ありがとうございます。こちらドキュメントではPlugins/のインストールはsubmoduleでの指定になっているので過去コミットへのcheckoutはできませんでした。
古いバージョンを使ってこれからのアップデートに追従できなくなると悲しいのでUE4.25.2をインストールして試すことにしました。早速ドキュメントの方も修正されているようで、こちら対応ありがとうございました。

**Comment by yosagi** [comment]
ドキュメントも修正しました。
余計な手間をかけさせてしまい申し訳ないです。

**Comment by asmsuechan** [comment]
とんでもございません。開発頑張ってください！
