### ISSUE TITLE
Unreal Engine 4.25.3で起動できない

### ISSUE THREAD

**Issue by rlabonct2020** [furo-org/VTC2018#8]
Unreal Engine 4.25.2はもうダウンロードできないので、どうすればUnreal Engine 4.25.3で起動できますか。

**Comment by yosagi** [comment]
手元で試した限り 4.15.2 と同じ手順で 4.25.3 でも特に問題なく起動するようです。起動できないとしたらバージョンの問題ではなく何か別の問題である可能性もあります。起動を試みたときにどうなるのかもう少し詳細に報告して頂けますでしょうか。

VTC/Saved/Logs/VTC.log にログが残っているはずですのでこれを見ると何か原因がわかるかもしれません。

なお、初回起動時(及びエンジンのバージョン更新後の初回起動時)はテクスチャなどアセットのビルドが入るのでスプラッシュスクリーンの95%あたりで、環境によっては1,2時間待たされます。

**Comment by rlabonct2020** [comment]
ご回答ありがとうございます。
.slnファイルを生成してビルドしたらできるようになりました。
v4.15.2とv4.25.3両方できました。
どうもありがとうございました。

**Comment by yosagi** [comment]
ドキュメントの4.25.2の箇所を4.25.3に修正しました。
