### ISSUE TITLE
PxArticulationLink Plugin がダウンロードできない

### ISSUE THREAD

**Issue by ghost** [furo-org/VTC2018#9]
https://github.com/furo-org/VTC/blob/TC2020/docs/editor.md
に従ってVTCの開発環境を整えようとしましたが、
update_submodule.batを実行したところ、
https://github.com/yosagi/PxArticulationLink.git
のリンクがGitHubから消えているらしく、
PxArticulationLink Pluginがダウンロードができません。
代替方法はございますでしょうか。

**Comment by kiyoshiiriemon** [comment]
そのリポジトリは制限付きアクセスなので、ページに書かれている
```
アカウントの準備

    まず最初にgithubのアカウントをまだ持っていなければ、(A)githubのページでgithubアカウントを作成します。
    次にUnrealEngineのページに行き、(B) EpicGamesのアカウントを作成し、(C) ゲームデベロッパーのEULAに同意し、(D) UnrealEngineをダウンロード/インストールします。ただ実際にはインストーラがインストールするのはEpic Games Launcherで、Unreal Engineそのもののインストールは手順が必要です(後述)。
    さらにUnreal Engineの接続済みアカウントのページで (E) Githubアカウントと接続します。
    その後GithubのEpicGamesのページに行き、(F) InvitationをAcceptします。

上記 (A) から (F) までうまくいけば、Unreal Engineのソースコードリポジトリにアクセスできるようになります。
```
の手順が正しく行われたか、再度ご確認ください。

**Comment by ghost** [comment]
kiyoshiiriemon様

手順内容を改めて確認しましたところ、
(F)の手順を見落としていたようです。
無事にダウンロードに成功致しました。
ご指摘のほど、ありがとうございました。

**Comment by yosagi** [comment]
ドキュメントのアカウントの準備のセクションで、必要なリポジトリにアクセスできるか確認してもらうよう促すことにしました。
